const BANDERAS = {
    'colombia': '🇨🇴',
    'brasil': '🇧🇷',
    'argentina': '🇦🇷',
    'uruguay': '🇺🇾',
    'ecuador': '🇪🇨',
    'peru': '🇵🇪',
    'perú': '🇵🇪',
    'chile': '🇨🇱',
    'paraguay': '🇵🇾',
    'bolivia': '🇧🇴',
    'venezuela': '🇻🇪',
    'mexico': '🇲🇽',
    'méxico': '🇲🇽',
    'espana': '🇪🇸',
    'españa': '🇪🇸',
    'alemania': '🇩🇪',
    'francia': '🇫🇷',
    'inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'portugal': '🇵🇹',
    'italia': '🇮🇹',
    'paises bajos': '🇳🇱',
    'países bajos': '🇳🇱',
    'holanda': '🇳🇱',
    'belgica': '🇧🇪',
    'bélgica': '🇧🇪',
    'croacia': '🇭🇷',
    'japon': '🇯🇵',
    'japón': '🇯🇵',
    'corea del sur': '🇰🇷',
    'estados unidos': '🇺🇸',
    'canada': '🇨🇦',
    'canadá': '🇨🇦',
    'marruecos': '🇲🇦',
    'senegal': '🇸🇳',
    'ghana': '🇬🇭',
    'nigeria': '🇳🇬',
    'camerun': '🇨🇲',
    'camerún': '🇨🇲',
    'tunez': '🇹🇳',
    'túnez': '🇹🇳',
    'arabia saudita': '🇸🇦',
    'catar': '🇶🇦',
    'qatar': '🇶🇦',
    'australia': '🇦🇺',
    'suiza': '🇨🇭',
    'polonia': '🇵🇱',
    'dinamarca': '🇩🇰',
    'serbia': '🇷🇸',
    'costa rica': '🇨🇷',
    'gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'sudafrica': '🇿🇦',
    'chequia': '🇨🇿',
    'bosnia y herzegovina': '🇧🇦',
    'curazao': '🇨🇼',
    'costa de marfil': '🇨🇮',
    'suecia': '🇸🇪',
    'cabo verde': '🇨🇻',
    'egipto': '🇪🇬',
    'iran': '🇮🇷',
    'irán': '🇮🇷',
    'nueva zelanda': '🇳🇿',
    'irak': '🇮🇶',
    'iraq': '🇮🇶',
    'noruega': '🇳🇴',
    'argelia': '🇩🇿',
    'austria': '🇦🇹',
    'jordania': '🇯🇴',
    'rd congo': '🇨🇩',
    'uzbekistan': '🇺🇿',
    'uzbekistán': '🇺🇿',
    'escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'panama': '🇵🇦',
    'panamá': '🇵🇦',
    'haiti': '🇭🇹',
    'haití': '🇭🇹',
    'turquia': '🇹🇷',
    'turquía': '🇹🇷',
};

export function bandera(equipo) {
    if (!equipo) return '⚽';
    return BANDERAS[equipo.trim().toLowerCase()] || '⚽';
}

// Códigos ISO 3166-1 alpha-2 (flagcdn.com) para mostrar banderas como imágenes circulares
const CODIGOS_PAISES = {
    'colombia': 'co',
    'brasil': 'br',
    'argentina': 'ar',
    'uruguay': 'uy',
    'ecuador': 'ec',
    'peru': 'pe',
    'perú': 'pe',
    'chile': 'cl',
    'paraguay': 'py',
    'bolivia': 'bo',
    'venezuela': 've',
    'mexico': 'mx',
    'méxico': 'mx',
    'espana': 'es',
    'españa': 'es',
    'alemania': 'de',
    'francia': 'fr',
    'inglaterra': 'gb-eng',
    'portugal': 'pt',
    'italia': 'it',
    'paises bajos': 'nl',
    'países bajos': 'nl',
    'holanda': 'nl',
    'belgica': 'be',
    'bélgica': 'be',
    'croacia': 'hr',
    'japon': 'jp',
    'japón': 'jp',
    'corea del sur': 'kr',
    'estados unidos': 'us',
    'canada': 'ca',
    'canadá': 'ca',
    'marruecos': 'ma',
    'senegal': 'sn',
    'ghana': 'gh',
    'nigeria': 'ng',
    'camerun': 'cm',
    'camerún': 'cm',
    'tunez': 'tn',
    'túnez': 'tn',
    'arabia saudita': 'sa',
    'catar': 'qa',
    'qatar': 'qa',
    'australia': 'au',
    'suiza': 'ch',
    'polonia': 'pl',
    'dinamarca': 'dk',
    'serbia': 'rs',
    'costa rica': 'cr',
    'gales': 'gb-wls',
    'sudafrica': 'za',
    'chequia': 'cz',
    'bosnia y herzegovina': 'ba',
    'curazao': 'cw',
    'costa de marfil': 'ci',
    'suecia': 'se',
    'cabo verde': 'cv',
    'egipto': 'eg',
    'iran': 'ir',
    'irán': 'ir',
    'nueva zelanda': 'nz',
    'irak': 'iq',
    'iraq': 'iq',
    'noruega': 'no',
    'argelia': 'dz',
    'austria': 'at',
    'jordania': 'jo',
    'rd congo': 'cd',
    'uzbekistan': 'uz',
    'uzbekistán': 'uz',
    'escocia': 'gb-sct',
    'panama': 'pa',
    'panamá': 'pa',
    'haiti': 'ht',
    'haití': 'ht',
    'turquia': 'tr',
    'turquía': 'tr',
};

export function codigoPais(equipo) {
    if (!equipo) return null;
    return CODIGOS_PAISES[equipo.trim().toLowerCase()] || null;
}
