const BANDERAS = {
    'colombia': '🇨🇴',
    'brasil': '🇧🇷',
    'argentina': '🇦🇷',
    'uruguay': '🇺🇾',
    'ecuador': '🇪🇨',
    'peru': '🇵🇪',
    'perú': '🇵🇪',
    'chile': '🇨🇱',
    'paraguay': '🇵🇾',
    'bolivia': '🇧🇴',
    'venezuela': '🇻🇪',
    'mexico': '🇲🇽',
    'méxico': '🇲🇽',
    'espana': '🇪🇸',
    'españa': '🇪🇸',
    'alemania': '🇩🇪',
    'francia': '🇫🇷',
    'inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'portugal': '🇵🇹',
    'italia': '🇮🇹',
    'paises bajos': '🇳🇱',
    'países bajos': '🇳🇱',
    'holanda': '🇳🇱',
    'belgica': '🇧🇪',
    'bélgica': '🇧🇪',
    'croacia': '🇭🇷',
    'japon': '🇯🇵',
    'japón': '🇯🇵',
    'corea del sur': '🇰🇷',
    'estados unidos': '🇺🇸',
    'canada': '🇨🇦',
    'canadá': '🇨🇦',
    'marruecos': '🇲🇦',
    'senegal': '🇸🇳',
    'ghana': '🇬🇭',
    'nigeria': '🇳🇬',
    'camerun': '🇨🇲',
    'camerún': '🇨🇲',
    'tunez': '🇹🇳',
    'túnez': '🇹🇳',
    'arabia saudita': '🇸🇦',
    'catar': '🇶🇦',
    'qatar': '🇶🇦',
    'australia': '🇦🇺',
    'suiza': '🇨🇭',
    'polonia': '🇵🇱',
    'dinamarca': '🇩🇰',
    'serbia': '🇷🇸',
    'costa rica': '🇨🇷',
    'gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'sudafrica': '🇿🇦',
    'chequia': '🇨🇿',
    'bosnia y herzegovina': '🇧🇦',
    'curazao': '🇨🇼',
    'costa de marfil': '🇨🇮',
    'suecia': '🇸🇪',
    'cabo verde': '🇨🇻',
    'egipto': '🇪🇬',
    'iran': '🇮🇷',
    'irán': '🇮🇷',
    'nueva zelanda': '🇳🇿',
    'irak': '🇮🇶',
    'iraq': '🇮🇶',
    'noruega': '🇳🇴',
    'argelia': '🇩🇿',
    'austria': '🇦🇹',
    'jordania': '🇯🇴',
    'rd congo': '🇨🇩',
    'uzbekistan': '🇺🇿',
    'uzbekistán': '🇺🇿',
    'escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'panama': '🇵🇦',
    'panamá': '🇵🇦',
    'haiti': '🇭🇹',
    'haití': '🇭🇹',
    'turquia': '🇹🇷',
    'turquía': '🇹🇷',
};

export function bandera(equipo) {
    if (!equipo) return '⚽';
    return BANDERAS[equipo.trim().toLowerCase()] || '⚽';
}
